import { hotelLandingPageData } from "@/app/hotel/hoteLandingPageData";
import { contact } from "@/utils/constent";
import {
  CarIcon,
  AcIcon,
  DoorIcon,
  BalconyIcon,
  WifiIcon,
  TvIcon,
  BathIcon,
  CameraIcon,
  GardenIcon,
  BottleIcon,
  WaterIcon,
  FreshenerIcon,
  BlenderIcon,
  BedIcon,
  IronIcon,
  CarSideIcon,
  SnowflakeIcon,
  FanIcon,
  FireExtinguisherIcon,
  FirstAidIcon,
  FridgeIcon,
  KettleIcon,
  DishesIcon,
  CoffeeIcon,
  WineIcon,
  BreadIcon,
} from "./AmenitiesIcons";

export const Icons = {
  car: CarIcon,
  ac: AcIcon,
  door: DoorIcon,
  balcony: BalconyIcon,
  wifi: WifiIcon,
  tv: TvIcon,
  bath: BathIcon,
  camera: CameraIcon,
  garden: GardenIcon,
  bottle: BottleIcon,
  water: WaterIcon,
  freshener: FreshenerIcon,
  blender: BlenderIcon,
  bed: BedIcon,
  iron: IronIcon,
  carSide: CarSideIcon,
  snowflake: SnowflakeIcon,
  fan: FanIcon,
  extinguisher: FireExtinguisherIcon,
  firstAid: FirstAidIcon,
  fridge: FridgeIcon,
  kettle: KettleIcon,
  dishes: DishesIcon,
  coffee: CoffeeIcon,
  wine: WineIcon,
  bread: BreadIcon,
};

export const roomsPageData = [
  {
    slug: "flora",
    metaData: {
      title: "Villa Flora – Luxury Private Villa Stay at Soul Storries",
      description:
        "Experience a serene escape at Villa Flora by Soul Storries. Enjoy luxury, privacy, and nature-inspired living in a beautifully designed villa retreat.",

      amenitiesData: [
        { icon: <CarIcon />, name: "Free parking on premises" },
        { icon: <AcIcon />, name: "AC – split-type ductless system" },
        { icon: <DoorIcon />, name: "Lock on bedroom door" },
        { icon: <BalconyIcon />, name: "Patio or balcony" },
        { icon: <WifiIcon />, name: "Wifi" },
        { icon: <TvIcon />, name: "TV" },
        { icon: <BathIcon />, name: "Bath" },
        { icon: <CameraIcon />, name: "Security cameras on property" },

        { icon: <GardenIcon />, name: "Garden view" },
        { icon: <BottleIcon />, name: "Shampoo" },
        { icon: <BottleIcon />, name: "Conditioner" },
        { icon: <WaterIcon />, name: "Hot water" },
        { icon: <FreshenerIcon />, name: "Shower gel" },
        { icon: <BlenderIcon />, name: "Essentials" },
        { icon: <BedIcon />, name: "Bed linen" },
        { icon: <IronIcon />, name: "Iron" },
        { icon: <CarSideIcon />, name: "Free parking on premises" },

        // { icon: "snowflake", name: "Central air conditioning" },
        // { icon: "fan", name: "Ceiling fan" },
        // { icon: "extinguisher", name: "Fire extinguisher" },
        // { icon: "firstAid", name: "First aid kit" },
        // { icon: "fridge", name: "Fridge" },
        // { icon: "kettle", name: "Kettle" },
        // { icon: "dishes", name: "Dishes and cutlery" },
        // { icon: "coffee", name: "Coffee maker" },
        // { icon: "wine", name: "Wine glasses" },
        // { icon: "bread", name: "Breakfast" },
      ],
    },
    title: "flora",
    description:
      "Travelling with a large family? Let us indulge you with a private entrance, a cozy fireplace, two spacious living areas, and four private bedrooms, each with an en-suite bathroom featuring both a bath and a shower. Welcome to Flora, a luxurious 4-bedroom chalet in Soul Storries, offering some of the most breathtaking mountain views in Mussoorie.",
    noOfBadRooms: hotelLandingPageData.rooms.cards[0].noOfBadRooms,
    images: hotelLandingPageData.rooms.cards[0].images,
    link: { label: "BOOK NOW", url: contact.WhatsappCta },
    amenitiesData: [
      { icon: <CarIcon />, name: "Free parking on premises" },
      { icon: <AcIcon />, name: "AC – split-type ductless system" },
      { icon: <DoorIcon />, name: "Lock on bedroom door" },
      { icon: <BalconyIcon />, name: "Patio or balcony" },
      { icon: <WifiIcon />, name: "Wifi" },
      { icon: <TvIcon />, name: "TV" },
      { icon: <BathIcon />, name: "Bath" },
      { icon: <CameraIcon />, name: "Security cameras on property" },

      { icon: <GardenIcon />, name: "Garden view" },
      { icon: <BottleIcon />, name: "Shampoo" },
      { icon: <BottleIcon />, name: "Conditioner" },
      { icon: <WaterIcon />, name: "Hot water" },
      { icon: <FreshenerIcon />, name: "Shower gel" },
      { icon: <BlenderIcon />, name: "Essentials" },
      { icon: <BedIcon />, name: "Bed linen" },
      { icon: <IronIcon />, name: "Iron" },
      { icon: <CarSideIcon />, name: "Free parking on premises" },

      // { icon: "snowflake", name: "Central air conditioning" },
      // { icon: "fan", name: "Ceiling fan" },
      // { icon: "extinguisher", name: "Fire extinguisher" },
      // { icon: "firstAid", name: "First aid kit" },
      // { icon: "fridge", name: "Fridge" },
      // { icon: "kettle", name: "Kettle" },
      // { icon: "dishes", name: "Dishes and cutlery" },
      // { icon: "coffee", name: "Coffee maker" },
      // { icon: "wine", name: "Wine glasses" },
      // { icon: "bread", name: "Breakfast" },
    ],
    safeAndHygienicData: {
      title: "Safe and Hygiene",
      items: [
        "Daily Cleaning",
        "Disinfections and Sterilizations",
        "Fire Extinguishers",
        "Smoke Detectors",
      ],
    },
  },
  {
    slug: "amaraa",
    metaData: {
      title: "Amaraa Luxury Villa | Soul Storries Villa Retreat in Nature",
      description:
        "Discover Amaraa, a serene luxury villa nestled in nature. Perfect for private retreats, peaceful getaways, and soulful experiences at Soul Storries.",
    },
    title: "amaraa",
    description:
      "One-bedroom villas provide a luxurious and comfortable retreat for those seeking a private and intimate stay experience with all the essential amenities and more.",
    noOfBadRooms: hotelLandingPageData.rooms.cards[1].noOfBadRooms,
    images: hotelLandingPageData.rooms.cards[1].images,
    link: { label: "BOOK NOW", url: contact.WhatsappCta },
    amenitiesData: [
      { icon: "car", name: "Free parking on premises" },
      { icon: "ac", name: "AC – split-type ductless system" },
      { icon: "door", name: "Lock on bedroom door" },
      { icon: "balcony", name: "Patio or balcony" },
      { icon: "wifi", name: "Wifi" },
      { icon: "tv", name: "TV" },
      { icon: "bath", name: "Bath" },
      { icon: "camera", name: "Security cameras on property" },

      { icon: "garden", name: "Garden view" },
      { icon: "bottle", name: "Shampoo" },
      { icon: "bottle", name: "Conditioner" },
      { icon: "water", name: "Hot water" },
      { icon: "freshener", name: "Shower gel" },
      { icon: "blender", name: "Essentials" },
      { icon: "bed", name: "Bed linen" },
      { icon: "iron", name: "Iron" },
      { icon: "snowflake", name: "Central air conditioning" },
      { icon: "fan", name: "Ceiling fan" },
      { icon: "extinguisher", name: "Fire extinguisher" },
      { icon: "firstAid", name: "First aid kit" },
      { icon: "fridge", name: "Fridge" },
      { icon: "kettle", name: "Kettle" },
      { icon: "dishes", name: "Dishes and cutlery" },
      { icon: "coffee", name: "Coffee maker" },
      { icon: "wine", name: "Wine glasses" },
      { icon: "bread", name: "Breakfast" },
    ],
    safeAndHygienicData: {
      title: "Safe and Hygiene",
      items: [
        "Daily Cleaning",
        "Disinfections and Sterilizations",
        "Fire Extinguishers",
        "Smoke Detectors",
      ],
    },
  },
  {
    slug: "aurora",
    metaData: {
      title: "Aurora: Luxury Private Villa | Soul Storries, Mussoorie",
      description: "Aurora: Luxury Private Villa | Soul Storries, Mussoorie",
    },
    title: "aurora",
    description:
      "If you’re a small group traveling together and seeking a balance of privacy with plenty of spaces to connect, Aurora at Soul Storries is your ideal stay. This stunning 2-bedroom, 1,700 sqft wooden chalet in Mussoorie offers a unique luxury experience, with several enchanting nooks that provide captivating views of the majestic Mussoorie mountains.",
    noOfBadRooms: hotelLandingPageData.rooms.cards[2].noOfBadRooms,
    images: hotelLandingPageData.rooms.cards[2].images,
    link: { label: "BOOK NOW", url: contact.WhatsappCta },
    amenitiesData: [
      { icon: "car", name: "Free parking on premises" },
      { icon: "ac", name: "AC – split-type ductless system" },
      { icon: "door", name: "Lock on bedroom door" },
      { icon: "balcony", name: "Patio or balcony" },
      { icon: "wifi", name: "Wifi" },
      { icon: "tv", name: "TV" },
      { icon: "bath", name: "Bath" },
      { icon: "camera", name: "Security cameras on property" },
      { icon: "garden", name: "Garden view" },
      { icon: "bottle", name: "Shampoo" },
      { icon: "bottle", name: "Conditioner" },
      { icon: "water", name: "Hot water" },
      { icon: "freshener", name: "Shower gel" },
      { icon: "blender", name: "Essentials" },
      { icon: "bed", name: "Bed linen" },
      { icon: "iron", name: "Iron" },
      { icon: "carSide", name: "Free parking on premises" },
      { icon: "wifi", name: "Wi-fi" },
      { icon: "snowflake", name: "Central air conditioning" },
      { icon: "fan", name: "Ceiling fan" },
      { icon: "extinguisher", name: "Fire extinguisher" },
      { icon: "firstAid", name: "First aid kit" },
      { icon: "fridge", name: "Fridge" },
      { icon: "kettle", name: "Kettle" },
      { icon: "dishes", name: "Dishes and cutlery" },
      { icon: "coffee", name: "Coffee maker" },
      { icon: "wine", name: "Wine glasses" },
      { icon: "bread", name: "Breakfast" },
    ],
    safeAndHygienicData: {
      title: "Safe and Hygiene",
      items: [
        "Daily Cleaning",
        "Disinfections and Sterilizations",
        "Fire Extinguishers",
        "Smoke Detectors",
      ],
    },
  },
  {
    slug: "aura",
    metaData: {
      title: "Aura Luxury Villa in Mussoorie - Private Wooden Chalet",
      description: "Experience unparalleled luxury at Aura, a private wooden chalet in Mussoorie offering a unique mountain stay with serene views, modern amenities, and exclusive tranquility.",
    },
    title: "aura",
    description:
      "Escape the confines of the corner office and immerse yourself in the misty charm of Aura, our exquisite corner villa. Offering unobstructed views of the majestic Himalayas, this one-bedroom, 800 sqft wooden chalet is the ultimate retreat for couples seeking a magical experience in Mussoorie.",
    noOfBadRooms: hotelLandingPageData.rooms.cards[3].noOfBadRooms,
    images: hotelLandingPageData.rooms.cards[3].images,
    link: { label: "BOOK NOW", url: contact.WhatsappCta },
    amenitiesData: [
      { icon: "car", name: "Free parking on premises" },
      { icon: "ac", name: "AC – split-type ductless system" },
      { icon: "door", name: "Lock on bedroom door" },
      { icon: "balcony", name: "Patio or balcony" },

      { icon: "wifi", name: "Wifi" },
      { icon: "tv", name: "TV" },
      { icon: "bath", name: "Bath" },
      { icon: "camera", name: "Security cameras on property" },

      { icon: "garden", name: "Garden view" },
      { icon: "bottle", name: "Shampoo" },
      { icon: "bottle", name: "Conditioner" },
      { icon: "water", name: "Hot water" },
      { icon: "freshener", name: "Shower gel" },
      { icon: "blender", name: "Essentials" },
      { icon: "bed", name: "Bed linen" },
      { icon: "iron", name: "Iron" },

      { icon: "wifi", name: "Wi-fi" },

      { icon: "snowflake", name: "Central air conditioning" },
      { icon: "fan", name: "Ceiling fan" },
      { icon: "extinguisher", name: "Fire extinguisher" },
      { icon: "firstAid", name: "First aid kit" },
      { icon: "fridge", name: "Fridge" },
      { icon: "kettle", name: "Kettle" },
      { icon: "dishes", name: "Dishes and cutlery" },
      { icon: "coffee", name: "Coffee maker" },
      { icon: "wine", name: "Wine glasses" },
      { icon: "bread", name: "Breakfast" },
    ],
    safeAndHygienicData: {
      title: "Safe and Hygiene",
      items: [
        "Daily Cleaning",
        "Disinfections and Sterilizations",
        "Fire Extinguishers",
        "Smoke Detectors",
      ],
    },
  },
  {
    slug: "athena",
    metaData: {
      title: "Athena Villa - Soul Storries Mussoorie",
      description: "Experience unparalleled serenity at Athena by Soul Storries, Mussoorie. Immerse yourself in luxury and nature with stunning views and top-notch amenities.",
    },
    title: "athena",
    description:
      "If you’re a small family seeking to create unforgettable memories in Mussoorie, Athena at Soul Storries is the perfect retreat for you. This luxurious 2-bedroom escape, covering 1,700 sqft, offers a private sanctuary of peace and relaxation, far from the noise and chaos of everyday life. The charming balcony, which doubles as a cozy family area, boasts breathtaking views that will leave you in awe of the beauty of the magical mountains.",
    noOfBadRooms: hotelLandingPageData.rooms.cards[5].noOfBadRooms,
    images: hotelLandingPageData.rooms.cards[5].images,
    link: { label: "BOOK NOW", url: contact.WhatsappCta },
    amenitiesData: [
      { icon: "car", name: "Free parking on premises" },
      { icon: "ac", name: "AC – split-type ductless system" },
      { icon: "door", name: "Lock on bedroom door" },
      { icon: "balcony", name: "Patio or balcony" },

      { icon: "wifi", name: "Wifi" },
      { icon: "tv", name: "TV" },
      { icon: "bath", name: "Bath" },
      { icon: "camera", name: "Security cameras on property" },

      { icon: "garden", name: "Garden view" },
      { icon: "bottle", name: "Shampoo" },
      { icon: "bottle", name: "Conditioner" },
      { icon: "water", name: "Hot water" },
      { icon: "freshener", name: "Shower gel" },
      { icon: "blender", name: "Essentials" },
      { icon: "bed", name: "Bed linen" },
      { icon: "iron", name: "Iron" },

      { icon: "wifi", name: "Wi-fi" },

      { icon: "snowflake", name: "Central air conditioning" },
      { icon: "fan", name: "Ceiling fan" },
      { icon: "extinguisher", name: "Fire extinguisher" },
      { icon: "firstAid", name: "First aid kit" },
      { icon: "fridge", name: "Fridge" },
      { icon: "kettle", name: "Kettle" },
      { icon: "dishes", name: "Dishes and cutlery" },
      { icon: "coffee", name: "Coffee maker" },
      { icon: "wine", name: "Wine glasses" },
      { icon: "bread", name: "Breakfast" },
    ],
    safeAndHygienicData: {
      title: "Safe and Hygiene",
      items: [
        "Daily Cleaning",
        "Disinfections and Sterilizations",
        "Fire Extinguishers",
        "Smoke Detectors",
      ],
    },
  },
];
